apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim      
      containers:
        - name: postgres
          image: postgres
          ports: 
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data/
          env: # kwestia obiektu secret omówiona w helpers/kubernetes
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            #ta zmienna zawiera info dla postgres gdzie są dane. Bez tego, zakłada default (val/lib/postgresql/data), w którym jest dir lost+found i nie chce kontynuować
            - name: PGDATA
              value: var/lib/postgresql/data/dbdata
